apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dwk-repo
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/santoser/devops-with-k8s
  ref:
    branch: master